# Generated by Django 4.1.2 on 2022-10-06 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='persona',
            new_name='Familiar',
        ),
    ]
