# Generated by Django 4.1.2 on 2022-10-06 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0002_rename_persona_familiar'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='fecha_nacimeinto',
            field=models.DateField(null=True),
        ),
    ]
