# Generated by Django 4.1.2 on 2022-10-06 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0003_familiar_fecha_nacimeinto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiar',
            old_name='fecha_nacimeinto',
            new_name='fecha_nacimiento',
        ),
    ]
