# Generated by Django 4.1.2 on 2022-10-06 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0004_rename_fecha_nacimeinto_familiar_fecha_nacimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiar',
            old_name='fecha_nacimiento',
            new_name='fecha_carga',
        ),
    ]
